name: Lint Code Base

on:
  push:
    branches: [1958-fix-css-linting-issues]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: 1958-fix-css-linting-issues
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          LINTER_RULES_PATH: /
          CSS_FILE_NAME: .stylelintrc.json
          VALIDATE_CSS: true